index:
  number_of_shards: 5
  number_of_replicas: 1


# Cluster Settings
cluster:
  name: RealTimeCongress

path:
  data: /var/lib/elasticsearch
  work: /mnt

http:
  port: 3145
  
bootstrap:
  mlockall: false
