# jekyll-specific
markdown: maruku
exclude: ["README.md", "todo.txt"]

maruku:
  fenced_code_blocks: true
# redcarpet:
#   extensions: ["no_intra_emphasis", "tables", "with_toc_data"]

# site-specific
google_analytics: "UA-22821126-30"
name: "Sunlight Congress API"
twitter: "sunlightlabs"