# jekyll-specific
markdown: kramdown
exclude: ["README.md", "todo.txt"]

pygments: true

# maruku:
#   fenced_code_blocks: true
kramdown:
  input: GFM
# redcarpet:
#   extensions: ["no_intra_emphasis", "tables", "with_toc_data"]

# site-specific
google_analytics: "UA-22821126-30"
name: "Sunlight Congress API"
twitter: "sunlightlabs"