exclude: ["README.md", "todo.txt"]

# markdown: kramdown + pygments, sigh
pygments: true
markdown: kramdown
kramdown:
  input: GFM

# jekyll supports a few plugins now
gems:
- jekyll-redirect-from

# site-specific
google_analytics: "UA-22821126-30"
name: "Sunlight Congress API"
twitter: "sunlightlabs"