cluster.name: Congress

index:
  number_of_shards: 5 # default
  number_of_replicas: 1 # default

path:
  data: /var/lib/elasticsearch
  work: /mnt

http:
  port: 3145

bootstrap:
  mlockall: true

node.master: true # default
node.data: true # default